server:
  port: 8080

spring:
  application:
    name: classmatehub-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classmatehub
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.thirteenash.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.thirteenash.mapper: debug
    org.springframework.web: debug